### ISSUE TITLE
Working in offline mode.

### ISSUE THREAD

**Issue by BEEugene** [petered/public-release#1]
Hi, thank you for the very useful tool! 
Is it possible to run this script to be able to copy and paste all used modules in one folder without Github?

**Comment by petered** [comment]
Yeah check out the example at the bottom of module_mover.py.  sorry about
the lack of documentation!

**Comment by petered** [comment]
For some reason it requires a package called Artemis, which it really
shouldn't. But you can get it with pip install artemis-ml

**Comment by BEEugene** [comment]
Thank you!
